/**
 * Shared workbench colors for Monaco + xterm (must stay in sync with index.css tokens).
 */

export const WORKBENCH = {
  dark: {
    bgDeep: '#0c0d10',
    bgPanel: '#111218',
    bgElevated: '#181a22',
    bgOverlay: '#1e2029',
    bgHover: 'rgba(255, 255, 255, 0.045)',
    bgActive: 'rgba(212, 168, 75, 0.14)',
    border: '#23252f',
    borderSoft: '#1a1c24',
    text: '#e6e4df',
    textMuted: '#8b8a93',
    accent: '#d4a84b',
    accentDim: '#a87a20',
    danger: '#d16b6b',
    success: '#8fbf7f',
    warn: '#d4a84b',
    info: '#7aa2c8',
    selection: '#d4a84b33',
    selectionInactive: '#d4a84b1a',
    lineHighlight: '#14161e',
    indentGuide: '#1e2028',
    indentGuideActive: '#32343e',
    ansi: {
      black: '#1a1b22',
      red: '#d16b6b',
      green: '#8fbf7f',
      yellow: '#d4a84b',
      blue: '#7aa2c8',
      magenta: '#b48ead',
      cyan: '#88c0d0',
      white: '#c8c6c0',
      brightBlack: '#5a5964',
      brightRed: '#e08080',
      brightGreen: '#a8d498',
      brightYellow: '#e0bc6a',
      brightBlue: '#94b8d8',
      brightMagenta: '#c8a0c0',
      brightCyan: '#a0d8e0',
      brightWhite: '#f0eee8',
    },
  },
  light: {
    bgDeep: '#eef0f4',
    bgPanel: '#f7f8fa',
    bgElevated: '#ffffff',
    bgOverlay: '#e8eaef',
    bgHover: 'rgba(0, 0, 0, 0.055)',
    bgActive: 'rgba(154, 111, 22, 0.16)',
    border: '#cfd3dc',
    borderSoft: '#dde1e8',
    text: '#12141a',
    textMuted: '#4f5160',
    accent: '#9a6f16',
    accentDim: '#7a5810',
    danger: '#b84a4a',
    success: '#3f8a38',
    warn: '#9a6f16',
    info: '#3a6f9e',
    selection: '#9a6f1633',
    selectionInactive: '#9a6f161a',
    lineHighlight: '#e6e8ee',
    indentGuide: '#d5d8e0',
    indentGuideActive: '#b0b4c0',
    ansi: {
      black: '#2a2b32',
      red: '#b84a4a',
      green: '#3f8a38',
      yellow: '#9a6f16',
      blue: '#3a6f9e',
      magenta: '#8a5a9a',
      cyan: '#2f7a7a',
      white: '#4f5160',
      brightBlack: '#6d6c76',
      brightRed: '#d16b6b',
      brightGreen: '#5aa850',
      brightYellow: '#c49a3a',
      brightBlue: '#5a92c0',
      brightMagenta: '#a070b0',
      brightCyan: '#4aa0a0',
      brightWhite: '#12141a',
    },
  },
};

export function workbench(themeMode = 'dark') {
  return themeMode === 'light' ? WORKBENCH.light : WORKBENCH.dark;
}

export function monacoThemeDef(themeMode = 'dark') {
  const c = workbench(themeMode);
  if (themeMode === 'light') {
    return {
      base: 'vs',
      inherit: true,
      rules: [
        { token: 'comment', foreground: '5a5c68', fontStyle: 'italic' },
        { token: 'keyword', foreground: '8a6418', fontStyle: 'bold' },
        { token: 'string', foreground: '2f6b2f' },
        { token: 'number', foreground: '8a6418' },
        { token: 'type', foreground: '2f5f8a' },
        { token: 'function', foreground: '7a5810' },
        { token: 'variable', foreground: '12141a' },
        { token: 'constant', foreground: '8a6418' },
      ],
      colors: {
        'editor.background': c.bgDeep,
        'editor.foreground': c.text,
        'editorCursor.foreground': c.accent,
        'editor.lineHighlightBackground': c.lineHighlight,
        'editor.selectionBackground': c.selection,
        'editor.inactiveSelectionBackground': c.selectionInactive,
        'editorLineNumber.foreground': '#7a7c88',
        'editorLineNumber.activeForeground': '#3a3c48',
        'editorGutter.background': c.bgDeep,
        'editorIndentGuide.background1': c.indentGuide,
        'editorIndentGuide.activeBackground1': c.indentGuideActive,
        'editorWidget.background': c.bgElevated,
        'editorWidget.border': c.border,
        'editorWidget.foreground': c.text,
        'editorSuggestWidget.background': c.bgElevated,
        'editorSuggestWidget.border': c.border,
        'editorSuggestWidget.foreground': c.text,
        'editorSuggestWidget.selectedBackground': c.bgActive,
        'editorSuggestWidget.selectedForeground': c.text,
        'editorSuggestWidget.highlightForeground': c.accent,
        'editorSuggestWidget.focusHighlightForeground': c.accent,
        'editorHoverWidget.background': c.bgElevated,
        'editorHoverWidget.border': c.border,
        'editorHoverWidget.foreground': c.text,
        'list.hoverBackground': c.bgHover,
        'list.activeSelectionBackground': c.bgActive,
        'list.activeSelectionForeground': c.text,
        'scrollbarSlider.background': '#4f516040',
        'scrollbarSlider.hoverBackground': '#4f516066',
        'minimap.background': c.bgDeep,
      },
    };
  }
  return {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '6d6c76', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'd4a84b' },
      { token: 'string', foreground: '9fc98f' },
      { token: 'number', foreground: 'c8a06a' },
      { token: 'type', foreground: '7aa2c8' },
      { token: 'function', foreground: 'e0c07a' },
      { token: 'variable', foreground: 'e6e4df' },
      { token: 'constant', foreground: 'c8a06a' },
    ],
    colors: {
      'editor.background': c.bgDeep,
      'editor.foreground': c.text,
      'editorCursor.foreground': c.accent,
      'editor.lineHighlightBackground': c.lineHighlight,
      'editor.selectionBackground': c.selection,
      'editor.inactiveSelectionBackground': c.selectionInactive,
      'editorLineNumber.foreground': '#6a6c78',
      'editorLineNumber.activeForeground': '#c8c6c0',
      'editorGutter.background': c.bgDeep,
      'editorIndentGuide.background1': c.indentGuide,
      'editorIndentGuide.activeBackground1': c.indentGuideActive,
      'editorBracketMatch.background': '#d4a84b22',
      'editorBracketMatch.border': '#d4a84b66',
      'editorWidget.background': c.bgElevated,
      'editorWidget.border': c.border,
      'editorWidget.foreground': c.text,
      'editorSuggestWidget.background': c.bgElevated,
      'editorSuggestWidget.border': c.border,
      'editorSuggestWidget.foreground': c.text,
      'editorSuggestWidget.selectedBackground': '#d4a84b33',
      'editorSuggestWidget.selectedForeground': '#f0eee8',
      'editorSuggestWidget.highlightForeground': c.accent,
      'editorSuggestWidget.focusHighlightForeground': c.accent,
      'editorHoverWidget.background': c.bgElevated,
      'editorHoverWidget.border': c.border,
      'editorHoverWidget.foreground': c.text,
      'list.hoverBackground': c.bgHover,
      'list.activeSelectionBackground': '#d4a84b33',
      'list.activeSelectionForeground': '#f0eee8',
      'scrollbarSlider.background': '#8b8a9340',
      'scrollbarSlider.hoverBackground': '#8b8a9366',
      'scrollbarSlider.activeBackground': '#8b8a9380',
      'minimap.background': c.bgDeep,
    },
  };
}

export function xtermTheme(themeMode = 'dark') {
  const c = workbench(themeMode);
  const a = c.ansi;
  return {
    background: c.bgDeep,
    foreground: c.text,
    cursor: c.accent,
    cursorAccent: c.bgDeep,
    selectionBackground: c.selection,
    selectionForeground: c.text,
    black: a.black,
    red: a.red,
    green: a.green,
    yellow: a.yellow,
    blue: a.blue,
    magenta: a.magenta,
    cyan: a.cyan,
    white: a.white,
    brightBlack: a.brightBlack,
    brightRed: a.brightRed,
    brightGreen: a.brightGreen,
    brightYellow: a.brightYellow,
    brightBlue: a.brightBlue,
    brightMagenta: a.brightMagenta,
    brightCyan: a.brightCyan,
    brightWhite: a.brightWhite,
  };
}

export const MONO_FONT =
  "'IBM Plex Mono', 'Cascadia Code', Consolas, Menlo, Monaco, monospace";
